baseURL = "http://tylerlubke.com"
languageCode = "en-us"
title = "tyler lubke - programmer|performer"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
enableInlineShortcodes = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "bio"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "music"
    url = "/music"
    weight = 2
[[menu.main]]
    name = "projects"
    url = "/projects"
    weight = 3

[params]
    description = "A website built through Hugo, using the xmin theme."
    footer =  "[Github](https://github.com/tlubke) | [Bandcamp](https://tylerlubke.bandcamp.com/)"
